
### Get my library (authenticated)
GET http://localhost:4000/api/libraries/
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4OWRjOTlhOC1mMDUyLTQzYWYtOGJjMi00MWExNGMxMzU2YjAiLCJpYXQiOjE3Njg1MjQwMjksImV4cCI6MTc2ODUyNzYyOX0.xBnbcoDEbST45E577TaWoCfPL_C7o_gpdfr8yBblmFE

### Add to my library
POST http://localhost:4000/api/libraries/
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4OWRjOTlhOC1mMDUyLTQzYWYtOGJjMi00MWExNGMxMzU2YjAiLCJpYXQiOjE3Njg1MjQwMjksImV4cCI6MTc2ODUyNzYyOX0.xBnbcoDEbST45E577TaWoCfPL_C7o_gpdfr8yBblmFE
Content-Type: application/json

{
  "bookId": "6f9ccea3-8b0e-4631-8b3d-8b6670256854",
  "title": "Murder on the Orient Express",
  "releaseDate": null,
  "isbn": null,
  "summary": "A young wizard discovers his magical heritage.",
  "authorId": "d7a4f3c1-2222-4b1d-9c10-bbbbbbbbbbbb",
  "status": "want_to_read"
}

### Delete book on my library

DELETE http://localhost:4000/api/libraries/6f9ccea3-8b0e-4631-8b3d-8b6670256854
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4OWRjOTlhOC1mMDUyLTQzYWYtOGJjMi00MWExNGMxMzU2YjAiLCJpYXQiOjE3Njg1MjQwMjksImV4cCI6MTc2ODUyNzYyOX0.xBnbcoDEbST45E577TaWoCfPL_C7o_gpdfr8yBblmFE
