### Register new user
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "email": "testuser@mail.com",
  "password": "Password123!"
}

### Login user (cookie is set)
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "testuser@mail.com",
  "password": "Password123!"
}

### Logout user (cookie is cleared)
POST http://localhost:4000/api/auth/logout